name: growana
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  flutter_svg: ^1.1.6

  # State Management & Storage
  provider: ^6.0.5
  shared_preferences: ^2.1.1

  # Location
  geolocator: ^10.1.0
  geocoding: ^4.0.0
  flutter_map: ^6.1.2
  latlong2: ^0.9.1

  # Network & API
  http: ^1.5.0
  url_launcher: ^6.2.2  # UNTUK BUKA MAPS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/